spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: haUTHRT7K_qxn9zbPuF2jLwl41B2NKU5
    url: jdbc:postgresql://raja.db.elephantsql.com:5432/fguqzpdu
    username: fguqzpdu
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

#server:
#  port: 7070
  