spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password:
    url:
    username: 
  jpa:
    database-platform: org.hibernate.dialect.PostgreSQLDialect
    properties:
      hibernate:
        temp:
          use_jdbc_metadata_defaults: false

#server:
#  port: 7070
  
